envvars:
    "HF_API_TOKEN"

rule all:
    input:
        "config.json"
    log:
        "logs/stderr.log",
        "logs/stdout.log",
    conda:
        "env.yaml"
    threads: 16
    params:
        hf_api_token=os.environ["HF_API_TOKEN"]
    script:
        "main.py"
