envvars:
    "HF_API_TOKEN"

rule all:
    log:
        "logs/stderr.log",
        "logs/stdout.log",
    conda:
        "envs/scrna_py.yaml"
    threads: 16
    params:
        hf_api_token=os.environ["HF_API_TOKEN"]
    script:
        "scripts/process.py"
